version: "3.9"
services:
  whm-api:
    build: .
    container_name: whm-api
    environment:
      - GO_ENV=production
      - GO_PORT=3000
    ports:
      - 3001:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
