version: "3.9"
services:
  whm-api:
    build: .
    restart: unless-stopped
    container_name: whm-api
    environment:
      - GO_ENV=$GO_ENV
      - GO_PORT=$GO_PORT
      - GIN_MODE=$GIN_MODE
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - VIRTUAL_HOST=$VIRTUAL_HOST_API
      - CLOUDFLARE_TOKEN=$CLOUDFLARE_TOKEN
      - USER_EMAIL=$USER_EMAIL
      - USER_PASSWORD=$USER_PASSWORD
      - AUTH_KEY=$AUTH_KEY
      - DEFAULT_USERNAME=$DEFAULT_USERNAME
      - DEFAULT_EMAIL=$DEFAULT_EMAIL
      - DEFAULT_PASSWORD=$DEFAULT_PASSWORD
      - SECURE_COOKIES=$SECURE_COOKIES
    ports:
      - "3001:3000"
    volumes:
      - ./whm-data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whm-db:
    image: postgres
    restart: unless-stopped
    container_name: whm-db
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports: 
      - "5432:5432"

  whm-auth:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:latest
    restart: unless-stopped
    container_name: whm-auth
    environment:
      - API_KEYS=$AUTH_KEY
      - VIRTUAL_HOST=$VIRTUAL_HOST_AUTH
    ports: 
      - "3567:3567"

networks:
  default:
    external:
      name: reverse-proxy-net

volumes:
  postgres-data: