version: "3.9"
services:
  whm-api:
    build: .
    restart: unless-stopped
    container_name: whm-api
    environment:
      - GO_ENV=production
      - GO_PORT=3000
      - POSTGRES_DB=whm-db
      - POSTGRES_USER=whm
      - POSTGRES_PASSWORD=whm-pass-123
      - VIRTUAL_HOST=api.antonwy.me
      - CLOUDFLARE_TOKEN=4sH0NB9cojjtKMeq3n4ln8IFxw3sG4aj4qYhtWG0
    ports:
      - 3001:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - reverse-proxy-net

  whm-db:
    image: postgres
    restart: unless-stopped
    container_name: whm-db
    environment:
      - POSTGRES_DB=whm-db
      - POSTGRES_USER=whm
      - POSTGRES_PASSWORD=whm-pass-123
    ports: 
      - 5432:5432
    networks:
        - reverse-proxy-net

networks:
  reverse-proxy-net:
    name: reverse-proxy-net
    external: true

volumes:
  postgres-data: