version: "3.9"
services:
  whm-api:
    build: .
    restart: unless-stopped
    container_name: whm-api
    environment:
      - GO_ENV=production
      - GO_PORT=3000
      - POSTGRES_DB=whm-db
      - POSTGRES_USER=whm
      - POSTGRES_PASSWORD=whm-pass-123
    ports:
      - 3001:3000
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./whm-data:/data

  whm-db:
    image: postgres
    restart: unless-stopped
    container_name: whm-db
    environment:
      - POSTGRES_DB=whm-db
      - POSTGRES_USER=whm
      - POSTGRES_PASSWORD=whm-pass-123
    ports: 
      - 5432:5432
    volumes:
        - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: whm-pg-admin
    depends_on:
      - postgres
    ports:
      - 5555:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=anton.wyrowski@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=AntonWy2002
    restart: unless-stopped

volumes:
  postgres-data: